language: java

dist: trusty

os:
  - linux
  - osx

before install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install tshark; fi

matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
        - os: osx
