package energybox.test;

import energybox.ConsoleBox;
import energybox.ProcessTraceOSX;
import energybox.UpdatesController;
import org.apache.commons.io.FileUtils;
import org.apache.commons.io.LineIterator;
import org.apache.commons.io.filefilter.FileFilterUtils;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;

/**
 * Verifies that the ConsoleBox/ProcessTraceOSX output matches that of previous, verified versions of EnergyBox.
 *
 * To use, provide (1) .pcaps to test and (2) output .csvs generated by a verified version of EnergyBox in GUI mode.
 *
 * File dependencies:
 * (1) Pcaps to test in:  src/test/resources/test*.pcap
 * (2) Oracle output csv: src/test/resources/oracle/test*.csv
 * Configs in:            src/test/resources/config/*.config
 */
public class CliOsXOutputTest {

    private File resources;
    private File configs;

    private enum TYPE {TYPE_3G, TYPE_WIFI}

    @Before
    public void setUp() throws Exception {
        URL resUrl = this.getClass().getResource("/test/resources/");
        this.resources = FileUtils.getFile(resUrl.getPath());

        URL cfgUrl = this.getClass().getResource("/test/resources/config");
        this.configs = FileUtils.getFile(cfgUrl.getPath());
    }

    @After
    public void tearDown() throws IOException {
        FileUtils.forceDelete(getTempFile());
    }

    @Test
    public void test3G_1() throws IOException {
        testOutput(1, getPcap("test1.pcap"), TYPE.TYPE_3G);
    }

    @Test
    public void test3G_2() throws IOException {
        testOutput(2, getPcap("test2.pcap"), TYPE.TYPE_3G);
    }

    @Test
    public void testWifi_1() throws IOException {
        testOutput(1, getPcap("test1.pcap"), TYPE.TYPE_WIFI);
    }

    @Test
    public void testWifi_2() throws IOException {
        testOutput(2, getPcap("test2.pcap"), TYPE.TYPE_WIFI);
    }

    private void testOutput(int number, File pcap, TYPE type) throws IOException {
        File networkConfig = getConfigNetwork(type);
        File deviceConfig = getConfigDevice(type);

        Map<String, String> flags = new HashMap<>();
        Collection<File> files = FileUtils.listFiles(resources, FileFilterUtils.trueFileFilter(), FileFilterUtils.trueFileFilter());
        flags.put("t", pcap.getAbsolutePath());
        flags.put("n", networkConfig.getAbsolutePath());
        flags.put("d", deviceConfig.getAbsolutePath());
        flags.put("f", getTempFile().getAbsolutePath());

        final UpdatesController updater = new ProcessTraceOSX.NullUpdater();
        final ProcessTraceOSX traceOSX = new ProcessTraceOSX(flags.get("t"), updater);
        traceOSX.run();
        ConsoleBox consoleBox = new ConsoleBox(traceOSX, flags.get("t"), flags.get("n"), flags.get("d"));
        consoleBox.printResults();

        if (flags.containsKey("f"))
        {
            consoleBox.outputToFile(flags.get("f"));
            System.out.println("States saved in file '" + flags.get("f") + "'");
        }

        File oracleCsv = getOracleCsv(number, type);
        File output = FileUtils.getFile(flags.get("f"));

        LineIterator itOracle = FileUtils.lineIterator(oracleCsv);
        LineIterator itOutput = FileUtils.lineIterator(output);

        // Oracle is generated using GUI.
        // CLI version prints source IP on line 1, Total power on line 2.
        assertEquals("First line is not source IP", traceOSX.getSourceIP(), itOutput.nextLine());
        // Expected power has been rounded.
        final double delta = 1e-4;
        assertEquals("Second line is not total power",
                consoleBox.getTotalPower(),
                Double.parseDouble(itOutput.nextLine()), delta);


        // Compare state output
        // States start at output line 3
        int outputLine = 3;
        try {
            while (itOracle.hasNext()) {
                String expected = itOracle.nextLine();
                String actual = itOutput.nextLine();
                outputLine++;
                assertEquals("Mismatch at line " + outputLine, expected, actual);
            }
        } finally {
            itOracle.close();
            itOutput.close();
        }
        assertFalse("Did not reach end of file. Stopped at line " + outputLine, itOracle.hasNext() || itOutput.hasNext());
    }

    private File getConfigNetwork(TYPE type) {
        switch (type) {
            case TYPE_3G:
                return FileUtils.getFile(configs, "3g_teliasonera.config");
            case TYPE_WIFI:
                return FileUtils.getFile(configs, "wifi_general.config");
        }
        throw new IllegalArgumentException();
    }

    private File getConfigDevice(TYPE type) {
        switch (type) {
            case TYPE_3G:
                return FileUtils.getFile(configs, "device_3g.config");
            case TYPE_WIFI:
                return FileUtils.getFile(configs, "samsungS2_wifi.config");
        }
        throw new IllegalArgumentException();
    }

    private File getPcap(String filename) {
        return FileUtils.getFile(resources, filename);
    }

    private File getTempFile() {
        return FileUtils.getFile(resources, "temp.pcap");
    }

    private File getOracleCsv(int number, TYPE type) {
        StringBuilder sb = new StringBuilder("oracle/test");
        sb.append(number);
        sb.append("_");
        switch (type) {
            case TYPE_3G:
                sb.append("3g");
                break;
            case TYPE_WIFI:
                sb.append("wifi");
                break;
            default:
                throw new IllegalArgumentException();
        }
        sb.append(".csv");
        return FileUtils.getFile(resources, sb.toString());
    }
}
