package energybox.test;

import energybox.ProcessTrace;
import energybox.ProcessTraceOSX;
import energybox.UpdatesController;

import java.util.Map;

/**
 * Verifies that the ConsoleBox/ProcessTrace output matches that of previous, verified versions of EnergyBox.
 *
 * Tests for the two different supported platforms are found in the subclasses CliOsXOutputTest and CliLibpcapOutputTest.
 * To use, provide (1) .pcaps to test and (2) output .csvs generated by a verified version of EnergyBox in GUI mode.
 *
 * File dependencies:
 * (1) Pcaps to test in:  src/test/resources/test*.pcap
 * (2) Oracle output csv: src/test/resources/oracle/test*.csv
 * Configs in:            src/test/resources/config/*.config
 */

public class CliOsXOutputTest extends CliOutputTest {
    @Override
    public ProcessTrace getImplementation(Map<String, String> flags, UpdatesController updater) {
        return new ProcessTraceOSX(flags.get("t"), updater);
    }
}
